# ============================================================
# EcoMove Platform - Configuration TEST
# ============================================================

# ---- Base de données H2 en mémoire (Tests) ----
spring.datasource.url=jdbc:h2:mem:ecomove_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ---- Serveur ----
server.port=8081

# ---- JWT Configuration ----
app.jwt.secret=EcoMoveTestSecretKeyForUnitTests2026VeryLongKeyForHMACSHA256Algorithm
app.jwt.expiration-ms=3600000

# ---- Swagger desactive en test ----
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ---- Logging ----
logging.level.root=WARN
logging.level.com.ecomove.ecoMove=DEBUG
