# ============================================================
# EcoMove Platform - Configuration Principale
# Date: 2026-03-06
# ============================================================

spring.application.name=EcoMove
spring.profiles.active=dev
